# Generated by Django 5.0.6 on 2024-06-22 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15, verbose_name='User name')),
                ('address', models.EmailField(max_length=30, verbose_name='Email Address')),
                ('password', models.CharField(max_length=30, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('numer', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_bonds', to='Bonds.userb')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonds_for_sale', to='Bonds.userb')),
            ],
        ),
    ]
