# Generated by Django 5.0.6 on 2024-06-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bonds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonds',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_bonds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonds',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonds_for_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserB',
        ),
    ]
